### PR TITLE
Fix #1394, #1391, #1370

### LINKED ISSUE #1370: TGMarker error handling
We will need a way to handle errors when adding markers to the map. Maybe tangram can throw an exception when `TGMarker#map` is set for an invalid marker?

cc/ @karimnaaji @msmollin

### LINKED ISSUE #1391: TGMarker.mm setMap attempts to return a boolean false but is marked as VOID
https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMarker.mm#L193

Seems to be a refactor artifact.

The question is - do we want to re-expose the boolean return? Because `setMap:` is getting synthesized into the `.map` property here https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMarker.h#L137

Overriding property setters has a requirement of a `void` return, otherwise you need to declare the setter explicitly as a function in the header. Not sure of the correct approach here given we  would like better error codes for some of this stuff per https://github.com/tangrams/tangram-es/issues/1370

### LINKED ISSUE #1394: Marker icon doesnt show if set before map
See the test code below:

```objc
TGMarker* markerPoint = [[TGMarker alloc] init];
markerPoint.stylingString = @"{ style: 'points', color: 'white', size: [52px, 52px], collide: false }";
markerPoint.point = coordinates;
// when set before icon, marker icon shows
//markerPoint.map = view;
markerPoint.icon = [UIImage imageNamed:@"mapzen_logo"];
// when set after icon, marker icon doesnt show
//markerPoint.map = view;
```

### PR DESCRIPTION
**Pull request by karimnaaji**
- Change properties to functions for marker usage to be able to return error status
- Return `NSError*` from this new interface
- Leave placeholder for future enum error code that can be returned through marker usage

Fixes #1394 
Fixes #1391 
Fixes #1370

### CODE REVIEW

File: platforms/ios/src/TangramMap/TGMarker.mm [hunk 1]
```diff
@@ -51,99 +62,148 @@ - (instancetype)initWithMapView:(TGMapViewController *)mapView
...
+    if (!tangramInstance->markerSetStylingFromPath(identifier, [path UTF8String])) {
+        return [self createNSError];
+    }
 
-    tangramInstance->markerSetStylingFromPath(identifier, [path UTF8String]);
+    return nil;
 }
 
-- (void)setPoint:(TGGeoPoint)coordinates
+- (NSError *)point:(TGGeoPoint)coordinates
```
Comment (sarahlensing) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Why did you choose to return an error as opposed to taking it as a parameter and returning a true if the call succeeded? The reason I ask is that this format seems more idiomatic for iOS dev (and will import into swift as a call marked as something that throws)

Comment (tallytalwar) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Based on the discussion from last week, I think that is what the consensus was, ie. Swift equivalent API should be marked to "throw" an exception.

Comment (karimnaaji) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Yes I first went what you are suggesting:

```objc
NSError* error;
BOOL success = [TGMarker point:coord error:&error];
if (!success) {
    // Use error
}
````
vs
```objc
NSError* error = [TGMarker point:coord];
if (error) {
   // Use error
}
```
I'm unsure what is the most common pattern here for iOS dev, so it can be changed to what you are  suggesting.

**Comment by tallytalwar** [comment]
So tested the NSError interface. It seems to just error with `domain` as TGMarker. But I think it does make sense to have it return the apt error. Or you were thinking of handling that in a subsequent PR, seeing that `TODO` marked in `createNSError` function.

File: platforms/ios/src/TangramMap/TGMarker.mm [hunk 2]
```diff
@@ -51,99 +62,148 @@ - (instancetype)initWithMapView:(TGMapViewController *)mapView
...
+                           userInfo:userInfo];
+}
+
+- (NSError *)stylingString:(NSString *)styling
 {
     _stylingString = styling;
     _stylingPath = nil;
 
-    if (!tangramInstance || !identifier) { return; }
+    if (!tangramInstance || !identifier) { return nil; }
```
Comment (karimnaaji) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Unsure, in a context where exception might be thrown out to the user this can become quite annoying, technically this is not an error _yet_ since you don't know whether the styling is valid or not here, but I was also wondering whether something should be thrown here, so I'm open to suggestions.

File: platforms/ios/src/TangramMap/TGMarker.mm [hunk 3]
```diff
@@ -51,99 +62,148 @@ - (instancetype)initWithMapView:(TGMapViewController *)mapView
...
-- (void)setStylingString:(NSString *)styling
+- (NSError *)createNSError
+{
+    NSMutableDictionary* userInfo = [[NSMutableDictionary alloc] init];
+    // TODO: add enum for object error
+    // [userInfo setObject: forKey:@"TGMarker"];
+
+    return [NSError errorWithDomain:@"TGMarker"
+                               code:0
+                           userInfo:userInfo];
```
Comment (karimnaaji) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Yes, it's just a placeholder for us to leave more information in the future.

File: platforms/ios/src/TangramMap/TGMarker.mm (hunk 2 above)
Comment (tallytalwar) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Yeah maybe an exception can be thrown for the user to the API to use it aptly, which is make sure a map instance is set before setting styling on a marker.

**Comment by karimnaaji** [comment]
@tallytalwar it does make sense. We have to handle that TODO when we address https://github.com/tangrams/tangram-es/issues/1370.

File: platforms/ios/src/TangramMap/TGMarker.mm (hunk 1 above)
Comment (sarahlensing) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Ah I didn't realize that. What you first had is a more common pattern.

File: platforms/ios/src/TangramMap/TGMarker.mm (hunk 2 above)
Comment (karimnaaji) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Ok sounds good, updating for that.

File: platforms/ios/src/TangramMap/TGMarker.mm (hunk 1 above)
Comment (karimnaaji) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Updated in https://github.com/tangrams/tangram-es/pull/1401/commits/7ad7f11c9171d53b4dfd3c4d02078e43deed91d7

File: platforms/ios/src/TangramMap/TGMarker.mm (hunk 2 above)
Comment (karimnaaji) [inline platforms/ios/src/TangramMap/TGMarker.mm]: Updating in https://github.com/tangrams/tangram-es/pull/1401/commits/7ad7f11c9171d53b4dfd3c4d02078e43deed91d7

File: platforms/ios/src/TangramMap/TGMarker.h [hunk 4]
```diff
@@ -77,52 +80,66 @@ NS_ASSUME_NONNULL_BEGIN
...
 /**
  Sets a marker styled to be a polyline (described in a `TGGeoPolyline`).
 
- @note Markers can have their geometry set multiple time wwith possibly different geometry types.
+ @param polyline the polyline geometry to set to this marker
+ @param error an error status pointer that will be assigned if non-nil and an error occured
+ @return Whether the marker polyline was set successfully
 
- @return An error if the marker can't be shown on the map
+ @note Markers can have their geometry set multiple time wwith possibly different geometry types.
```
Comment (tallytalwar) [inline platforms/ios/src/TangramMap/TGMarker.h]: nit pick, spelling `with`.

**Comment by sarahlensing** [comment]
@tallytalwar @tallytalwar Changes LGTM 👍
