### PR TITLE
Synchronize access to shared NativeMap

### LINKED ISSUE #2136: Crash on disposing map (0.12.0)
On tangram-es 0.12.0, on Android Lollipop, I get the following crash report. I can reliably reproduce it by just ending the app.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapData.remove()' on a null object reference
        at com.mapzen.tangram.MapController.dispose(MapController.java:220)
```

Don't ask me how this can ever be null. Looking at the Java code, it doesn't look like this is possible.

(For completeness sake, here is the full stacktrace:)
```
01-23 16:01:04.912 24835-24835/de.westnordost.streetcomplete.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 24835
    java.lang.RuntimeException: Unable to destroy activity {de.westnordost.streetcomplete.debug/de.westnordost.streetcomplete.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapData.remove()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3812)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830)
        at android.app.ActivityThread.access$1400(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:5389)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapData.remove()' on a null object reference
        at com.mapzen.tangram.MapController.dispose(MapController.java:220)
        at com.mapzen.tangram.MapView.disposeMap(MapView.java:262)
        at com.mapzen.tangram.MapView.onDestroy(MapView.java:312)
        at de.westnordost.streetcomplete.map.MapFragment.onDestroy(MapFragment.kt:94)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment.onDestroy(LocationAwareMapFragment.kt:97)
        at de.westnordost.streetcomplete.map.QuestsMapFragment.onDestroy(QuestsMapFragment.kt:84)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2830)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2825)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:233)
        at android.app.Activity.performDestroy(Activity.java:6169)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3799)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:211) 
        at android.app.ActivityThread.main(ActivityThread.java:5389) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
```

### PR DESCRIPTION
**Pull request by matteblair**
Addresses https://github.com/tangrams/tangram-es/issues/2218

The change that resolved the crashes was to declare (almost) all the methods of `NativeMap` as `synchronized`. Earlier versions of these method declarations had been `synchronized`, but this was dropped in https://github.com/tangrams/tangram-es/pull/2187. The original reason for making these `synchronized` (which I have now rediscovered) is that `MapController` and `MapRenderer` both call methods with mutable access to native memory from separate threads. Occasionally, these method calls can interleave and lead to states that produce a crash. For example, `MapController` may add a marker to the map while `MapRenderer` is iterating over the list of markers, invalidating the iterator and causing a segmentation fault.

Forcing the UI thread and GL thread to synchronize on the same object is less than ideal because the GL thread can be blocked and drop frames, but avoiding these data races without synchronization would require significant refactoring.

Several other changes got rolled into this PR while I was trying various solutions:
- Resolves #2136 by refactoring disposal of `MapData`
- Changes `Map::Impl::scene` from `shared_ptr` to `unique_ptr`, for clearer ownership
- Fixes a lot of warnings from Android Studio

### CODE REVIEW

**Comment by matteblair** [comment]
@westnordost @tapetis If either of you are able, could you test out this build on Android 11 and try to reproduce the segmentation fault?

[tangram-release-1e5e02c.aar.zip](https://github.com/tangrams/tangram-es/files/5752710/tangram-release-1e5e02c.aar.zip)

**Comment by tapetis** [comment]
I think the number of crashes has decreased with the new version, but I still encountered the following `SIGSEGV` (with pointer tagging enabled):

```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0 in tid 4936 (GLThread 21145), pid 4507 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.201205.008/6943376:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2020-12-30 15:01:20+0100
pid: 4507, tid: 4936, name: GLThread 21145  >>> de.westnordost.streetcomplete.debug <<<
uid: 10384
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0
Cause: null pointer dereference
    x0  0000000000000000  x1  b4000077e7993548  x2  0000000000000000  x3  00000076d724cf18
    x4  00000076133e3ee8  x5  000000000000004a  x6  31234901ff302349  x7  7f7f7f7f7f7f7f7f
    x8  b4000077e79932b0  x9  0000000000000021  x10 0000000000000015  x11 0000000000000000
    x12 0000000000000025  x13 00000076133e3fd8  x14 0000000000000000  x15 00000000ebad6a89
    x16 0000007669d12198  x17 000000796b3b6dd4  x18 00000075e0546000  x19 b4000076f790ad10
    x20 0000000000000000  x21 0000000000000000  x22 0000000000000000  x23 00000000178c7800
    x24 0000fd4670af4807  x25 00000000178c76d0  x26 0000000000000000  x27 0000000000000000
    x28 00000076133e3ff0  x29 00000076133e3fa0
    lr  000000766979bcd0  sp  00000076133e3f70  pc  000000766979bcec  pst 0000000040001000
backtrace:
      #00 pc 0000000000059cec  /data/app/~~DF1OlZxFTn0Qcr6aM17FPQ==/de.westnordost.streetcomplete.debug-e8xo9YbLsLv0XS9zULeSBA==/lib/arm64/libtangram.so (BuildId: 3dbe5fc9c4bd14195530e569d05b579cc2ff9621)
      #01 pc 00000000000566e4  /data/app/~~DF1OlZxFTn0Qcr6aM17FPQ==/de.westnordost.streetcomplete.debug-e8xo9YbLsLv0XS9zULeSBA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: 3dbe5fc9c4bd14195530e569d05b579cc2ff9621)
      #02 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #03 pc 0000000002079550  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapzen.tangram.MapRenderer.onDrawFrame+224)
      #04 pc 000000000207aae4  /memfd:jit-cache (deleted) (offset 0x2000000) (android.opengl.GLSurfaceView$GLThread.guardedRun+3172)
      #05 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #06 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #08 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #09 pc 000000000067d794  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #10 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 000000000034bf24  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #12 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #14 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #16 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #17 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #20 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```

Additionally, the NPE described in #2136 is still present.

**Comment by matteblair** [comment]
The latest change addresses https://github.com/tangrams/tangram-es/issues/2136. I was able to reproduce that exception reliably and I've corrected the root cause (will explain in that issue). I believe these two issues may be related. Because of the exception in `MapData.remove()` the `onDestroy()` call in StreetComplete has to be wrapped in a try/catch block, but that means that `MapController.dispose()` stops when the first exception is thrown and doesn't finish cleaning up the native memory. This might be why there is a crash in native code shortly after this.

@tapetis Can you try another build? Thank you so much for your help and patience. 
[tangram-release-2ac49fb.aar.zip](https://github.com/tangrams/tangram-es/files/5758300/tangram-release-2ac49fb.aar.zip)

**Comment by westnordost** [comment]
Nice!

Am 31. Dezember 2020 22:24:23 MEZ schrieb Matt Blair <notifications@github.com>:
>The latest change addresses
>https://github.com/tangrams/tangram-es/issues/2136. I was able to
>reproduce that exception reliably and I've corrected the root cause
>(will explain in that issue). I believe these two issues may be
>related. Because of the exception in `MapData.remove()` the
>`onDestroy()` call in StreetComplete has to be wrapped in a try/catch
>block, but that means that `MapController.dispose()` stops when the
>first exception is thrown and doesn't finish cleaning up the native
>memory. This might be why there is a crash in native code shortly after
>this.
>
>@tapetis Can you try another build? Thank you so much for your help and
>patience. 
>[tangram-release-2ac49fb.aar.zip](https://github.com/tangrams/tangram-es/files/5758300/tangram-release-2ac49fb.aar.zip)
> 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tangrams/tangram-es/pull/2223#issuecomment-753181325

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tapetis** [comment]
With the latest version, #2136 seems to be fixed. However, I encountered three other crashes during my brief testing. These crashes include two `SIGSEGV` (pointer tagging was enabled).

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 21159
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.NativeMap.updateCameraPosition(int, double, double, float, float, float, float, float, float, double, double, double, double, android.graphics.Rect, float, int)' on a null object reference
        at com.mapzen.tangram.MapController.updateCameraPosition(MapController.java:411)
        at com.mapzen.tangram.MapController.updateCameraPosition(MapController.java:363)
        at de.westnordost.streetcomplete.map.tangram.CameraManager.pushCameraPositionToController(CameraManager.kt:169)
        at de.westnordost.streetcomplete.map.tangram.CameraManager.animate(CameraManager.kt:174)
        at de.westnordost.streetcomplete.map.tangram.CameraManager.access$animate(CameraManager.kt:36)
        at de.westnordost.streetcomplete.map.tangram.CameraManager$animateCameraUpdate$6.invoke(CameraManager.kt:158)
        at de.westnordost.streetcomplete.map.tangram.CameraManager$animateCameraUpdate$6.invoke(CameraManager.kt:36)
        at de.westnordost.streetcomplete.map.tangram.CameraManagerKt$sam$android_animation_ValueAnimator_AnimatorUpdateListener$0.onAnimationUpdate(Unknown Source:2)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:987)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1357)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1489)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0 in tid 22214 (GLThread 24526), pid 21565 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.201205.008/6943376:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-01-01 15:42:12+0100
pid: 21565, tid: 22214, name: GLThread 24526  >>> de.westnordost.streetcomplete.debug <<<
uid: 10388
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0
Cause: null pointer dereference
    x0  0000000000000000  x1  b4000077e7861258  x2  0000000000000000  x3  00000076d724cf18
    x4  000000765fe84ee8  x5  000000000000004a  x6  31234901ff302349  x7  7f7f7f7f7f7f7f7f
    x8  b4000077e7860fc0  x9  0000000000000021  x10 0000000000000015  x11 0000000000000000
    x12 0000000000000025  x13 000000765fe84fd8  x14 0000000000000000  x15 00000000ebad6a89
    x16 0000007669c11198  x17 000000796b3b6dd4  x18 0000007621af6000  x19 b4000076f7b10ea0
    x20 0000000000000000  x21 0000000000000000  x22 0000000000000000  x23 0000000017813018
    x24 0001287e1a61c7cc  x25 0000000017812ee8  x26 0000000000000000  x27 0000000000000000
    x28 000000765fe84ff0  x29 000000765fe84fa0
    lr  000000766969acd0  sp  000000765fe84f70  pc  000000766969acec  pst 0000000040000000
backtrace:
      #00 pc 0000000000059cec  /data/app/~~3IQGNEU6eArsutCrPv6KHw==/de.westnordost.streetcomplete.debug-gTeM4YCfgwIjry3eobWtLA==/lib/arm64/libtangram.so (BuildId: 3dbe5fc9c4bd14195530e569d05b579cc2ff9621)
      #01 pc 00000000000566e4  /data/app/~~3IQGNEU6eArsutCrPv6KHw==/de.westnordost.streetcomplete.debug-gTeM4YCfgwIjry3eobWtLA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: 3dbe5fc9c4bd14195530e569d05b579cc2ff9621)
      #02 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #03 pc 0000000002092670  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapzen.tangram.MapRenderer.onDrawFrame+224)
      #04 pc 000000000207e774  /memfd:jit-cache (deleted) (offset 0x2000000) (android.opengl.GLSurfaceView$GLThread.guardedRun+3172)
      #05 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #06 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #08 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #09 pc 000000000067d794  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #10 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 000000000034bf24  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #12 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #14 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #16 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #17 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #20 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0 in tid 22937 (GLThread 24512), pid 22545 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.201205.008/6943376:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-01-01 15:46:38+0100
pid: 22545, tid: 22937, name: GLThread 24512  >>> de.westnordost.streetcomplete.debug <<<
uid: 10388
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0
Cause: null pointer dereference
    x0  0000000000000000  x1  b4000077e78882c8  x2  0000000000000000  x3  00000076d724cf18
    x4  0000007656371608  x5  000000000000004a  x6  31234901ff302349  x7  7f7f7f7f7f7f7f7f
    x8  b4000077e7888030  x9  0000000000000021  x10 0000000000000015  x11 0000000000000000
    x12 0000000000000025  x13 00000076563716f8  x14 0000000000000000  x15 00000000ebad6a89
    x16 0000007669c54198  x17 000000796b3b6dd4  x18 000000762256e000  x19 b4000076f79ae3f0
    x20 0000000000000000  x21 0000000000000000  x22 0000000000000000  x23 b400007847916618
    x24 00000076bba8e000  x25 0000007656373000  x26 0000000000000cfa  x27 0000000000000002
    x28 0000007656371710  x29 00000076563716c0
    lr  00000076696ddcd0  sp  0000007656371690  pc  00000076696ddcec  pst 0000000040000000
backtrace:
      #00 pc 0000000000059cec  /data/app/~~3IQGNEU6eArsutCrPv6KHw==/de.westnordost.streetcomplete.debug-gTeM4YCfgwIjry3eobWtLA==/lib/arm64/libtangram.so (BuildId: 3dbe5fc9c4bd14195530e569d05b579cc2ff9621)
      #01 pc 00000000000566e4  /data/app/~~3IQGNEU6eArsutCrPv6KHw==/de.westnordost.streetcomplete.debug-gTeM4YCfgwIjry3eobWtLA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: 3dbe5fc9c4bd14195530e569d05b579cc2ff9621)
      #02 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #03 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #04 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #05 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #06 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 000000000067b118  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #08 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #09 pc 00000000002942d8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~3IQGNEU6eArsutCrPv6KHw==/de.westnordost.streetcomplete.debug-gTeM4YCfgwIjry3eobWtLA==/base.apk] (com.mapzen.tangram.MapRenderer.onDrawFrame+60)
      #10 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #12 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 000000000207b834  /memfd:jit-cache (deleted) (offset 0x2000000) (android.opengl.GLSurfaceView$GLThread.guardedRun+3172)
      #14 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #16 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #17 pc 0000000000305cf4  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 000000000030dc24  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 000000000030e61c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #20 pc 000000000067d794  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #21 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #22 pc 000000000034bf24  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #23 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #24 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #25 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #26 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #27 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #28 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #29 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #30 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #31 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```

**Comment by matteblair** [comment]
Here is another build to try with the latest changes. 

[tangram-release-56d1d1e.aar.zip](https://github.com/tangrams/tangram-es/files/5763835/tangram-release-56d1d1e.aar.zip)

I was able to map the null pointer dereference crashes to [this line in map.cpp](https://github.com/tangrams/tangram-es/blob/56d1d1eb7041e13db876fa2ddb135b2837aba201/core/src/map.cpp#L231). I am honestly a bit mystified as to how this is occurring. I have refactored the related code and it might not fix the crash but it should at least cause it to crash differently, which will help track down the root cause.

The first crash you posted (the exception on updateCameraPosition) looks to me like a bug in the application code. This exception indicates that a method was called on a MapController after it was disposed, i.e. after its MapView was destroyed.

**Comment by tapetis** [comment]
Here are three crashes with the latest build:

```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 3944 (GLThread 29520), pid 2424 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.201205.008/6943376:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-01-04 18:38:09+0100
pid: 2424, tid: 3944, name: GLThread 29520  >>> de.westnordost.streetcomplete.debug <<<
uid: 10393
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000011  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000080  x6  6e7171641f6e6cff  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  0f9b306c01e8b15a  x10 00000000c3ba724b  x11 00000000f78ee180
    x12 00000000b5c169c2  x13 0000000000000018  x14 0000000000000000  x15 00000000000000aa
    x16 000000766bf529e8  x17 00000079697dcb30  x18 00000075e7eee000  x19 0000000000000011
    x20 0000000000000000  x21 00000000ffffffff  x22 0000000000000001  x23 b40000775836d1e0
    x24 0000000000000000  x25 b4000076e78610b0  x26 000000760faed000  x27 0000000000000000
    x28 000000760faebff0  x29 000000760faebe50
    lr  000000766ba2a120  sp  000000760faebde0  pc  000000766bae8c44  pst 0000000060001000
backtrace:
      #00 pc 0000000000165c44  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #01 pc 00000000000a711c  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #02 pc 00000000000a61ac  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #03 pc 00000000000b4844  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #04 pc 00000000000599d4  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #05 pc 00000000000566e4  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #06 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 000000000210aca0  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapzen.tangram.MapRenderer.onDrawFrame+224)
      #08 pc 00000000020a1514  /memfd:jit-cache (deleted) (offset 0x2000000) (android.opengl.GLSurfaceView$GLThread.guardedRun+3172)
      #09 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #10 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #12 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 000000000067d794  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #14 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 000000000034bf24  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #16 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #17 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #20 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #21 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #22 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #23 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #24 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x240a413f90a913 in tid 10335 (GLThread 29531), pid 10131 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.201205.008/6943376:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-01-04 18:56:51+0100
pid: 10131, tid: 10335, name: GLThread 29531  >>> de.westnordost.streetcomplete.debug <<<
uid: 10393
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x240a413f90a913
    x0  bc240a413f90a90b  x1  bc240a413f90a90b  x2  0000000000000011  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000080  x6  6e7171641f6e6cff  x7  7f7f7f7f7f7f7f7f
    x8  bc240a413f90a90b  x9  0f9b306c01e8b15a  x10 00000076676e8b51  x11 0000000000000001
    x12 0000000000000018  x13 b4000077b78a0d78  x14 b4000077f7898c48  x15 00000076676e8b51
    x16 0000000000000000  x17 0000000000000200  x18 000000762a546000  x19 0000000000000011
    x20 bc240a413f90a90b  x21 00000000ffffffff  x22 0000000000000001  x23 b400007757a27180
    x24 0000000000000000  x25 b4000076e787caf0  x26 00000076676ea000  x27 0000000000000000
    x28 00000076676e8df0  x29 00000076676e8c50
    lr  000000766972c120  sp  00000076676e8be0  pc  00000076697eac44  pst 0000000060000000
backtrace:
      #00 pc 0000000000165c44  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #01 pc 00000000000a711c  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #02 pc 00000000000a61ac  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #03 pc 00000000000b4844  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #04 pc 00000000000599d4  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #05 pc 00000000000566e4  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #06 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #08 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #09 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #10 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 000000000067b118  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #12 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 0000000000294398  [anon:dalvik-classes.dex extracted in memory from /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/base.apk] (com.mapzen.tangram.MapRenderer.onDrawFrame+60)
      #14 pc 000000000067cdf0  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #16 pc 000000000034b92c  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.guardedRun+1092)
      #17 pc 000000000067da34  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1248) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 000000000034bf24  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #20 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #21 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #22 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #23 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #24 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #25 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #26 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #27 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #28 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0 in tid 7208 (GLThread 29425), pid 6854 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.201205.008/6943376:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-01-04 18:47:00+0100
pid: 6854, tid: 7208, name: GLThread 29425  >>> de.westnordost.streetcomplete.debug <<<
uid: 10393
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0
Cause: null pointer dereference
    x0  0000000000000000  x1  b4000077e7899770  x2  0000000000000000  x3  00000076d724cf18
    x4  00000076c6bdbee8  x5  000000000000004a  x6  31234901ff302349  x7  7f7f7f7f7f7f7f7f
    x8  b4000077e7899500  x9  0000000000000021  x10 0000000000000015  x11 0000000000000000
    x12 0000000000000025  x13 00000076c6bdbfd8  x14 0000000000000000  x15 00000000ebad6a89
    x16 0000007668c17198  x17 000000796b3b6dd4  x18 0000007660d98000  x19 b4000076f7a7d1b0
    x20 0000000000000000  x21 0000000000000000  x22 0000000000000000  x23 00000000133d0e00
    x24 0001656308cb97d9  x25 00000000133d0cd0  x26 0000000000000000  x27 0000000000000000
    x28 00000076c6bdbff0  x29 00000076c6bdbfa0
    lr  00000076686a1978  sp  00000076c6bdbf70  pc  00000076686a1994  pst 0000000040001000
backtrace:
      #00 pc 0000000000059994  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #01 pc 00000000000566e4  /data/app/~~8Hwmps8giwFbxmOqJQxjAQ==/de.westnordost.streetcomplete.debug-2OwJZ7L8RardxZUbzA_dKA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: cd1d7f84a718856365e6743154921cc6427937b9)
      #02 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #03 pc 0000000002024e30  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapzen.tangram.MapRenderer.onDrawFrame+224)
      #04 pc 0000000002040c04  /memfd:jit-cache (deleted) (offset 0x2000000) (android.opengl.GLSurfaceView$GLThread.guardedRun+3172)
      #05 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #06 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #08 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #09 pc 000000000067d794  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #10 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 000000000034bf24  /system/framework/framework.jar (offset 0x92a000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #12 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #14 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #16 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #17 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #20 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```

**Comment by matteblair** [comment]
I was able to build the StreetComplete app using my local version of Tangram ES and test it on Android 11 devices using the AWS Device Farm. In remote testing sessions I was able to eventually reproduce a crash, and logcat output showed that it was the same stack trace reported here. Now that I am able to semi-reliably reproduce the crash myself, debugging it is much easier!

From testing, I determined that a race condition was occurring in scene load calls and I applied synchronization to fix it. With this change, I've been unable to reproduce the crash again. However thread safety bugs are probabilistic by nature, so it's possible there are more conditions that I haven't covered yet. 

@tapetis if you or anyone else is interested, here is one more build to test. [tangram-release-b1f987b.aar.zip](https://github.com/tangrams/tangram-es/files/5835031/tangram-release-b1f987b.aar.zip)

If I don't encounter more crashes I plan to merge this and call it solved for now!

**Comment by tapetis** [comment]
I have found one additional crash with the latest build that occurs infrequently:
```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 8049 (GLThread 19256), pid 7841 (tcomplete.debug)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/flame/flame:11/RQ1A.210105.003/7005429:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
Timestamp: 2021-01-19 17:50:32+0100
pid: 7841, tid: 8049, name: GLThread 19256  >>> de.westnordost.streetcomplete.debug <<<
uid: 10416
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000013  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000080  x6  6e7171641f6e6cff  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  268d49ee74f42363  x10 00000000ee7cecf5  x11 00000000d9e7b130
    x12 000000001139836c  x13 00001602b8f63cf6  x14 0024f5fd92483159  x15 00000000169538a1
    x16 0000007942f549e8  x17 0000007c4b9ebb30  x18 0000007925350000  x19 0000000000000013
    x20 0000000000000000  x21 00000000ffffffff  x22 0000000000000001  x23 0000007a39e70d50
    x24 0000000000000000  x25 00000079c9eb1a30  x26 00000079514fa000  x27 0000000000000000
    x28 00000079514f8df0  x29 00000079514f8c50
    lr  0000007942a2c124  sp  00000079514f8be0  pc  0000007942aeac54  pst 0000000060001000
backtrace:
      #00 pc 0000000000165c54  /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/lib/arm64/libtangram.so (BuildId: ac7ef032e5dea657d5f0cdfb8538ab31100e6336)
      #01 pc 00000000000a7120  /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/lib/arm64/libtangram.so (BuildId: ac7ef032e5dea657d5f0cdfb8538ab31100e6336)
      #02 pc 00000000000a61b0  /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/lib/arm64/libtangram.so (BuildId: ac7ef032e5dea657d5f0cdfb8538ab31100e6336)
      #03 pc 00000000000b4848  /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/lib/arm64/libtangram.so (BuildId: ac7ef032e5dea657d5f0cdfb8538ab31100e6336)
      #04 pc 00000000000599d4  /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/lib/arm64/libtangram.so (BuildId: ac7ef032e5dea657d5f0cdfb8538ab31100e6336)
      #05 pc 00000000000566e4  /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/lib/arm64/libtangram.so (Java_com_mapzen_tangram_NativeMap_update+24) (BuildId: ac7ef032e5dea657d5f0cdfb8538ab31100e6336)
      #06 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #07 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #08 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #09 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #10 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #11 pc 000000000067b118  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #12 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #13 pc 00000000002963f8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~NlVsx_DCfL9PNfjpQj7gSg==/de.westnordost.streetcomplete.debug-HXXKrcqw_YU2G2QpOO7JDA==/base.apk] (com.mapzen.tangram.MapRenderer.onDrawFrame+60)
      #14 pc 000000000067cdf0  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #15 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #16 pc 000000000034aa30  /system/framework/framework.jar (offset 0x92b000) (android.opengl.GLSurfaceView$GLThread.guardedRun+1092)
      #17 pc 000000000067da34  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1248) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #18 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #19 pc 000000000034b028  /system/framework/framework.jar (offset 0x92b000) (android.opengl.GLSurfaceView$GLThread.run+48)
      #20 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #21 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #22 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #23 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #24 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #25 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #26 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: c820164b0c64ea40f1abc53aaf588b44)
      #27 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
      #28 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 95f68a34fdf7b31f42d3f811d5d88f58)
```

File: core/src/map.cpp [hunk 1]
```diff
@@ -155,8 +151,10 @@ SceneID Map::Impl::loadScene(SceneOptions&& _sceneOptions) {
 
 SceneID Map::Impl::loadSceneAsync(SceneOptions&& _sceneOptions) {
 
-    // Avoid to keep loading old scene and tiles
-    auto oldScene = std::move(scene);
+    // Move the previous scene into a shared_ptr so that it can be captured in a std::function
+    // (unique_ptr can't be captured because std::function is copyable).
+    std::shared_ptr<Scene> oldScene = std::move(scene);
```
Comment (tallytalwar) [inline core/src/map.cpp:156]: Wow that's interesting. I am not sure if this is a recommended practice but also don't know what's another solution for this. Initial usage of shared ptr for the scene itself was to get around this.. but it came with  it's own tentacles.

File: core/src/map.cpp [hunk 2]
```diff
@@ -169,9 +167,12 @@ SceneID Map::Impl::loadSceneAsync(SceneOptions&& _sceneOptions) {
         platform.requestRender();
     };
 
-    scene = std::make_shared<Scene>(platform, std::move(_sceneOptions), prefetchCallback);
+    scene = std::make_unique<Scene>(platform, std::move(_sceneOptions), prefetchCallback);
 
-    asyncWorker->enqueue([this, newScene = scene]() {
+    // This async task gets a raw pointer to the new scene and the following task takes ownership of the shared_ptr to
```
Comment (tallytalwar) [inline core/src/map.cpp:172]: Thanks for documenting this.

File: platforms/android/tangram/src/main/cpp/NativeMap.cpp [hunk 3]
```diff
@@ -505,6 +501,8 @@ jlong NATIVE_METHOD(addClientDataSource)(JNIEnv* env, jobject obj,
 void NATIVE_METHOD(removeClientDataSource)(JNIEnv* env, jobject obj, jlong sourcePtr) {
     auto* map = androidMapFromJava(env, obj);
     auto* clientDataSource = reinterpret_cast<ClientDataSource*>(sourcePtr);
+    // Map holds the only reference of the shared_ptr to the ClientDataSource, so removing the
```
Comment (tallytalwar) [inline platforms/android/tangram/src/main/cpp/NativeMap.cpp:504]: Thanks for documenting this.

File: platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java [hunk 4]
```diff
@@ -204,19 +204,32 @@ void UIThreadInit(@NonNull final GLViewHolder viewHolder, @Nullable final HttpHa
      * Responsible to dispose internals of MapController during Map teardown.
      * If client code extends MapController and overrides this method, then it must call super.dispose()
      */
-    protected synchronized void dispose() {
-
+    protected void dispose() {
```
Comment (tallytalwar) [inline platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java:207]: Why take the synchronize call out here? Could you add some information to the code for that, just that someone (me) doesn't go and add it back in!

File: platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java [hunk 5]
```diff
@@ -204,19 +204,32 @@ void UIThreadInit(@NonNull final GLViewHolder viewHolder, @Nullable final HttpHa
...
         }
         clientTileSources.clear();
         markers.clear();
 
+        // NativeMap dispose makes GL calls to free GPU resources so we _should_ call it on the
+        // render thread, where the GL context is active. However, it is possible for the render
+        // thread associated with GLSurfaceView to be stopped without running all of the queued
+        // events. This would cause the native memory to be leaked.
+        //
+        // To avoid this, we dispose the NativeMap on the UI thread. The GL calls produce an
```
Comment (tallytalwar) [inline platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java:225]: I vaguely remember a similar thing when having a texture view setup for the gl context. Maybe update the comment to use generic gl context(y) instead of specific to glsurfaceview.

Comment (tallytalwar) [reply platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java:225]: Ahh I see you moved the comment (I added) here. So note to past me to do that. Thanks Matt

File: platforms/android/tangram/src/main/java/com/mapzen/tangram/MapRenderer.java [hunk 6]
```diff
@@ -106,17 +102,21 @@ void captureFrame(MapController.FrameCaptureCallback callback, boolean waitForCo
 
     @NonNull
     private Bitmap capture() {
-        View view = map.getGLViewHolder().getView();
+        GLViewHolder viewHolder = map.getGLViewHolder();
+        if (viewHolder == null) {
+            throw new IllegalStateException("MapController GLViewHolder is null");
```
Comment (tallytalwar) [inline platforms/android/tangram/src/main/java/com/mapzen/tangram/MapRenderer.java:107]: Is this possible? How? Out of memory?

**Review by tallytalwar — CHANGES_REQUESTED** [review]
Thanks Matt. These changes are looking clean, could you clarify a couple of things here?

I think over the years we have gone back and forth with these synchronized calls, so if you could put some code comments around the ones you took out would be good.

P.S. sorry if there are any typos , reviewing from github mobile app (which is surprisingly quite good) .

File: core/src/map.cpp (hunk 1 above)
Comment (matteblair) [reply core/src/map.cpp:156]: Yeah I thought about this bit a lot. `unique_ptr` is a better fit for ownership of the scene, it just makes async disposal messier. What would be ideal here is a non-copyable version of `std::function` (there are implementations of this in other projects) but using a `shared_ptr` here seemed like a decent balance between elegance and pragmatism.

File: platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java (hunk 4 above)
Comment (matteblair) [reply platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java:207]: I see your point, but I'm not sure what to document because this `synchronized` wasn't actually doing anything. Before the earlier JNI refactor `MapController` was the object that native methods synchronized on, but now nothing else synchronizes on `MapController`.

File: platforms/android/tangram/src/main/java/com/mapzen/tangram/MapRenderer.java (hunk 6 above)
Comment (matteblair) [reply platforms/android/tangram/src/main/java/com/mapzen/tangram/MapRenderer.java:107]: `getGLViewHolder()` is declared `@Nullable`, which generates a warning unless the result is checked for nullity before accessing it.

**Review by tallytalwar — APPROVED** [review]
Thanks Matt for addressing the comments. LGTM
