### PR TITLE
Fix non-square bitmap images flipping

### LINKED ISSUE #1156: Marker setDrawable
wheh I call function setDrawable, I have exception 

> java.lang.ArrayIndexOutOfBoundsException: length=1152; index=1152

### PR DESCRIPTION
**Pull request by tallytalwar**
- Fixes #1156

### CODE REVIEW

File: core/src/marker/markerManager.cpp [hunk 1]
```diff
@@ -72,6 +72,11 @@ bool MarkerManager::setBitmap(MarkerID markerID, int width, int height, const un
     texture->setData(bitmapData, size);
 
     marker->setTexture(std::move(texture));
+
+    // The geometry is unchanged, but the mesh must be rebuilt because DynamicQuadMesh contains
+    // texture batches as part of its data.
+    buildGeometry(*marker, m_zoom);
```
Comment (tallytalwar) [inline core/src/marker/markerManager.cpp]: can you do a `return buildGeometry(*marker, m_zoom)` here?

Comment (blair1618) [inline core/src/marker/markerManager.cpp]: I wrote that at first, but I think it could actually be kind of misleading. For instance, if you call `setBitmap` on a marker before you set the styling or geometry, then the call would return `false` even though the bitmap was successfully assigned to the marker.

Comment (blair1618) [inline core/src/marker/markerManager.cpp]: Hmm I'd rather have the failure communicated from another function. To fully specify a marker, an application has to call `setStyling` and `setPoint`, `setPolyline`, or `setPolygon`, so to me it makes more sense to return an indication of failed geometry from the geometry setting functions.

Comment (blair1618) [inline core/src/marker/markerManager.cpp]: And this whole thing has reinforced to me how convoluted it can be to put a marker on the map. There's gotta be something better we can do :\

Comment (tallytalwar) [inline core/src/marker/markerManager.cpp]: Sure, sounds good.
