### PR TITLE
Fix bad reference on scene when fetching textures asynchronously

### LINKED ISSUE #829: Occassional crash in `getTexture()` when loading remote scenes with NSURL
Running the OS X demo app with a remote scene file will sometimes result in a crash with a stack trace similar to this:
```
Process:               tangram [26757]
Path:                  /Users/USER/*/tangram.app/Contents/MacOS/tangram
Identifier:            com.mapzen.tangram
Version:               1.0 (1.0)
Code Type:             X86-64 (Native)
Parent Process:        zsh [1500]
Responsible:           Terminal [556]
User ID:               501

Date/Time:             2016-07-13 11:47:12.930 -0400
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        6583FAB3-5BC5-2A93-4017-BC1ECB457DCF

Sleep/Wake UUID:       81B7882E-1210-4045-B8C0-877C0765CE81

Time Awake Since Boot: 36000 seconds
Time Since Wake:       980 seconds

System Integrity Protection: disabled

Crashed Thread:        5  Dispatch queue: NSOperationQueue 0x7fa30861ac00 :: NSOperation 0x7fa30d62acf0 (QOS: LEGACY)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000561382050

VM Regions Near 0x561382050:
    MALLOC_LARGE           0000000112521000-00000001125cf000 [  696K] rw-/rwx SM=PRV  
--> 
    STACK GUARD            0000700000000000-0000700000001000 [    4K] ---/rwx SM=NUL  stack guard for thread 1

Global Trace Buffer (reverse chronological seconds):
3.171904     CFNetwork                  0x00007fff976393cb TCP Conn 0x7fa30af1d820 SSL Handshake DONE
3.172117     CFNetwork                  0x00007fff976393cb TCP Conn 0x7fa30af69240 SSL Handshake DONE
3.181453     CFNetwork                  0x00007fff976392a7 TCP Conn 0x7fa30af69240 starting SSL negotiation
3.181536     CFNetwork                  0x00007fff976392a7 TCP Conn 0x7fa30af1d820 starting SSL negotiation
3.181569     CFNetwork                  0x00007fff97637c71 TCP Conn 0x7fa30af69240 complete. fd: 15, err: 0
3.181699     CFNetwork                  0x00007fff97637c71 TCP Conn 0x7fa30af1d820 complete. fd: 14, err: 0
3.181715     CFNetwork                  0x00007fff976c654b TCP Conn 0x7fa30af69240 event 1. err: 0
3.182265     CFNetwork                  0x00007fff976c654b TCP Conn 0x7fa30af1d820 event 1. err: 0
3.193280     CFNetwork                  0x00007fff97636f43 TCP Conn 0x7fa30af1d820 started
3.193679     CFNetwork                  0x00007fff97636f43 TCP Conn 0x7fa30af69240 started
4.445619     CFNetwork                  0x00007fff976393cb TCP Conn 0x7fa308445cc0 SSL Handshake DONE
4.546388     CFNetwork                  0x00007fff976392a7 TCP Conn 0x7fa308445cc0 starting SSL negotiation
4.546591     CFNetwork                  0x00007fff97637c71 TCP Conn 0x7fa308445cc0 complete. fd: 9, err: 0
4.546926     CFNetwork                  0x00007fff976c654b TCP Conn 0x7fa308445cc0 event 1. err: 0
4.565193     CFNetwork                  0x00007fff97636f43 TCP Conn 0x7fa308445cc0 started
4.658840     CFNetwork                  0x00007fff975fabc6 Creating default cookie storage with process/bundle identifier
4.658840     CFNetwork                  0x00007fff975fab5e Faulting in CFHTTPCookieStorage singleton
4.658888     CFNetwork                  0x00007fff975fa9ed Faulting in NSHTTPCookieStorage singleton

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff966dbf72 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff966db3b3 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91e741c4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91e7368c __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91e72ed8 CFRunLoopRunSpecific + 296
5   com.apple.HIToolbox             0x00007fff8eab4935 RunCurrentEventLoopInMode + 235
6   com.apple.HIToolbox             0x00007fff8eab476f ReceiveNextEventCommon + 432
7   com.apple.HIToolbox             0x00007fff8eab45af _BlockUntilNextEventMatchingListInModeWithFilter + 71
8   com.apple.AppKit                0x00007fff9b6fadf6 _DPSNextEvent + 1067
9   com.apple.AppKit                0x00007fff9b6fa226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
10  com.mapzen.tangram              0x000000010a3a461a _glfwPlatformWaitEvents + 90 (cocoa_window.m:1110)
11  com.mapzen.tangram              0x000000010a06cfab main + 1435 (main.cpp:379)
12  libdyld.dylib                   0x00007fff8ce255ad start + 1

Thread 1:
0   libsystem_malloc.dylib          0x00007fff90343792 tiny_malloc_from_free_list + 214
1   libsystem_malloc.dylib          0x00007fff90342705 szone_malloc_should_clear + 292
2   libsystem_malloc.dylib          0x00007fff903425a1 malloc_zone_malloc + 71
3   com.apple.CoreFoundation        0x00007fff91ded4bd _CFRuntimeCreateInstance + 301
4   com.apple.CoreFoundation        0x00007fff91e05246 _CFURLCreateWithURLString + 2230
5   com.apple.Foundation            0x00007fff8ce5a2b7 -[NSURL(NSURL) initWithString:relativeToURL:] + 356
6   com.apple.Foundation            0x00007fff8ce5a12c +[NSURL(NSURL) URLWithString:relativeToURL:] + 59
7   com.mapzen.tangram              0x000000010a067e8f startUrlRequest(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::vector<char, std::__1::allocator<char> >&&)>) + 495 (platform_osx.mm:159)
8   com.mapzen.tangram              0x000000010a2002ea Tangram::SceneLoader::fetchTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Tangram::TextureOptions const&, bool, Tangram::Scene&) + 5882 (sceneLoader.cpp:541)
9   com.mapzen.tangram              0x000000010a1e3a58 Tangram::SceneLoader::loadTexture(std::__1::pair<YAML::Node, YAML::Node> const&, Tangram::Scene&) + 2168 (sceneLoader.cpp:636)
10  com.mapzen.tangram              0x000000010a1d9698 Tangram::SceneLoader::applyConfig(YAML::Node&, Tangram::Scene&) + 10104 (sceneLoader.cpp:193)
11  com.mapzen.tangram              0x000000010a1d6e51 Tangram::SceneLoader::loadScene(std::__1::shared_ptr<Tangram::Scene>) + 305 (sceneLoader.cpp:61)
12  com.mapzen.tangram              0x000000010a3060d0 Tangram::loadSceneAsync(char const*, bool, std::__1::function<void ()>)::$_0::operator()() const + 176 (tangram.cpp:180)
13  com.mapzen.tangram              0x000000010a30600d void std::__1::__invoke_void_return_wrapper<void>::__call<Tangram::loadSceneAsync(char const*, bool, std::__1::function<void ()>)::$_0&>(Tangram::loadSceneAsync(char const*, bool, std::__1::function<void ()>)::$_0&&&) + 45 (__functional_base:469)
14  com.mapzen.tangram              0x000000010a305d19 std::__1::__function::__func<Tangram::loadSceneAsync(char const*, bool, std::__1::function<void ()>)::$_0, std::__1::allocator<Tangram::loadSceneAsync(char const*, bool, std::__1::function<void ()>)::$_0>, void ()>::operator()() + 41 (functional:1437)
15  com.mapzen.tangram              0x000000010a31152e std::__1::function<void ()>::operator()() const + 126 (functional:1817)
16  com.mapzen.tangram              0x000000010a314b7c Tangram::AsyncWorker::run() + 588 (asyncWorker.h:46)
17  com.mapzen.tangram              0x000000010a3157b4 void* std::__1::__thread_proxy<std::__1::tuple<void (Tangram::AsyncWorker::*)(), Tangram::AsyncWorker*> >(void*) + 532 (__functional_base:383)
18  libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
19  libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
20  libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib          0x00007fff966e25e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff94d4e578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff94d4c341 start_wqthread + 13

Thread 3:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib          0x00007fff966e2efa kevent_qos + 10
1   libdispatch.dylib               0x00007fff96043165 _dispatch_mgr_invoke + 216
2   libdispatch.dylib               0x00007fff96042dcd _dispatch_mgr_thread + 52

Thread 4:
0   libsystem_kernel.dylib          0x00007fff966e25e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff94d4e578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff94d4c341 start_wqthread + 13

Thread 5 Crashed:: Dispatch queue: NSOperationQueue 0x7fa30861ac00 :: NSOperation 0x7fa30d62acf0 (QOS: LEGACY)
0   com.mapzen.tangram              0x000000010a1d608b std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<Tangram::Texture> >, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<Tangram::Texture> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<Tangram::Texture> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<Tangram::Texture> >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<Tangram::Texture> > > >::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const + 411 (__hash_table:2046)
1   com.mapzen.tangram              0x000000010a1d2e8d Tangram::Scene::getTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const + 109 (unordered_map:1144)
2   com.mapzen.tangram              0x000000010a211bde Tangram::SceneLoader::fetchTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Tangram::TextureOptions const&, bool, Tangram::Scene&)::$_0::operator()(std::__1::vector<char, std::__1::allocator<char> >&&) const + 190 (sceneLoader.cpp:545)
3   com.mapzen.tangram              0x000000010a211b0d void std::__1::__invoke_void_return_wrapper<void>::__call<Tangram::SceneLoader::fetchTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Tangram::TextureOptions const&, bool, Tangram::Scene&)::$_0&, std::__1::vector<char, std::__1::allocator<char> > >(Tangram::SceneLoader::fetchTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Tangram::TextureOptions const&, bool, Tangram::Scene&)::$_0&&&, std::__1::vector<char, std::__1::allocator<char> >&&) + 77 (__functional_base:469)
4   com.mapzen.tangram              0x000000010a211829 std::__1::__function::__func<Tangram::SceneLoader::fetchTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Tangram::TextureOptions const&, bool, Tangram::Scene&)::$_0, std::__1::allocator<Tangram::SceneLoader::fetchTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Tangram::TextureOptions const&, bool, Tangram::Scene&)::$_0>, void (std::__1::vector<char, std::__1::allocator<char> >&&)>::operator()(std::__1::vector<char, std::__1::allocator<char> >&&) + 57 (functional:1437)
5   com.mapzen.tangram              0x000000010a068b31 std::__1::function<void (std::__1::vector<char, std::__1::allocator<char> >&&)>::operator()(std::__1::vector<char, std::__1::allocator<char> >&&) const + 145 (functional:1817)
6   com.mapzen.tangram              0x000000010a068272 ___Z15startUrlRequestRKNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS_8functionIFvONS_6vectorIcS4_EEEEE_block_invoke + 770 (platform_osx.mm:153)
7   com.apple.CFNetwork             0x00007fff9761b775 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 21
8   com.apple.CFNetwork             0x00007fff9761b043 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 302
9   com.apple.Foundation            0x00007fff8ce6d8d7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
10  com.apple.Foundation            0x00007fff8ce6d595 -[NSBlockOperation main] + 100
11  com.apple.Foundation            0x00007fff8ce6bc7a -[__NSOperationInternal _start:] + 654
12  com.apple.Foundation            0x00007fff8ce67c64 __NSOQSchedule_f + 194
13  libdispatch.dylib               0x00007fff9603d40b _dispatch_client_callout + 8
14  libdispatch.dylib               0x00007fff9604203b _dispatch_queue_drain + 754
15  libdispatch.dylib               0x00007fff96048707 _dispatch_queue_invoke + 549
16  libdispatch.dylib               0x00007fff96040d53 _dispatch_root_queue_drain + 538
17  libdispatch.dylib               0x00007fff96040b00 _dispatch_worker_thread3 + 91
18  libsystem_pthread.dylib         0x00007fff94d4e4de _pthread_wqthread + 1129
19  libsystem_pthread.dylib         0x00007fff94d4c341 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib          0x00007fff966e25e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff94d4e578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff94d4c341 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib          0x00007fff966e25e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff94d4e578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff94d4c341 start_wqthread + 13

Thread 8:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x00007fff966dbf72 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff966db3b3 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91e741c4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91e7368c __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91e72ed8 CFRunLoopRunSpecific + 296
5   com.apple.CFNetwork             0x00007fff975fe095 +[NSURLConnection(Loader) _resourceLoadLoop:] + 412
6   com.apple.Foundation            0x00007fff8ce5be64 __NSThread__start__ + 1351
7   libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
8   libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
9   libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 9:: com.apple.NSEventThread
0   libsystem_kernel.dylib          0x00007fff966dbf72 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff966db3b3 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff91e741c4 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff91e7368c __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff91e72ed8 CFRunLoopRunSpecific + 296
5   com.apple.AppKit                0x00007fff9b850d95 _NSEventThread + 149
6   libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
7   libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
8   libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 10:: OGL Profiler
0   libsystem_kernel.dylib          0x00007fff966dbf72 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff966db3b3 mach_msg + 55
2   com.apple.opengl                0x00007fff9c832a7b glcDebugListener + 333
3   libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
4   libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
5   libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 11:: com.apple.CFSocket.private
0   libsystem_kernel.dylib          0x00007fff966e207a __select + 10
1   com.apple.CoreFoundation        0x00007fff91eb14fa __CFSocketManager + 762
2   libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
3   libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
4   libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 12:
0   libsystem_kernel.dylib          0x00007fff966e1dce __psynch_mutexdrop + 10
1   libsystem_pthread.dylib         0x00007fff94d4ed8c _pthread_mutex_unlock_drop + 60
2   libc++.1.dylib                  0x00007fff93822fa3 std::__1::mutex::unlock() + 9
3   com.mapzen.tangram              0x000000010a3561b7 Tangram::TileWorker::run(Tangram::TileWorker::Worker*) + 6471 (__mutex_base:132)
4   com.mapzen.tangram              0x000000010a35a8b7 void* std::__1::__thread_proxy<std::__1::tuple<void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*> >(void*) + 567 (__functional_base:383)
5   libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
6   libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
7   libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 13:
0   libsystem_kernel.dylib          0x00007fff966e1de6 __psynch_mutexwait + 10
1   libsystem_pthread.dylib         0x00007fff94d4ee4a _pthread_mutex_lock_wait + 89
2   libc++.1.dylib                  0x00007fff93822f6d std::__1::mutex::lock() + 9
3   com.mapzen.tangram              0x000000010a3549be Tangram::TileWorker::run(Tangram::TileWorker::Worker*) + 334 (__mutex_base:110)
4   com.mapzen.tangram              0x000000010a35a8b7 void* std::__1::__thread_proxy<std::__1::tuple<void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*> >(void*) + 567 (__functional_base:383)
5   libsystem_pthread.dylib         0x00007fff94d4e99d _pthread_body + 131
6   libsystem_pthread.dylib         0x00007fff94d4e91a _pthread_start + 168
7   libsystem_pthread.dylib         0x00007fff94d4c351 thread_start + 13

Thread 14:
0   libsystem_kernel.dylib          0x00007fff966e25e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff94d4e578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff94d4c341 start_wqthread + 13

Thread 5 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fa3086b9440  rcx: 0x00007fa308628788  rdx: 0x00000000ac27040a
  rdi: 0x676e69646c697562  rsi: 0x000000010a6e97f0  rbp: 0x000070000021c4a0  rsp: 0x000070000021c0f0
   r8: 0x0000000000000040   r9: 0x000000000004f1f5  r10: 0x000000000004f1ee  r11: 0x0000000000000206
  r12: 0x00007fa30d613e80  r13: 0x00007fa30d62ad70  r14: 0x00007fff916734c0  r15: 0x00007fa30d613d80
  rip: 0x000000010a1d608b  rfl: 0x0000000000010246  cr2: 0x0000000561382050
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14
```

### PR DESCRIPTION
**Pull request by karimnaaji**
Should fix #829 . 

For safer use in async tasks, use a shared_ptr to the scene (retained in the lambda functions to fetch textures). What happens is that the reference to the scene used at the beginning of the [scene loader pipeline](https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L61) would become inconsistent in the lambda functions and could potentially result in bad access, since it's copying the address of the reference [here](https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L541).

### CODE REVIEW

File: core/src/tangram.cpp [hunk 1]
```diff
@@ -229,7 +229,7 @@ void applySceneUpdates() {
```
Comment (hjanetzek) [inline core/src/tangram.cpp]: Here the shared_ptr<Scene> is copied so ```scene``` remains valid during ```applyConfig```. There is a minimal race-condition though as the copying of m_nextScene is not synchronized

File: core/src/scene/sceneLoader.cpp [hunk 2]
```diff
@@ -520,36 +520,36 @@ bool SceneLoader::extractTexFiltering(Node& filtering, TextureFiltering& filter)
...
 
     std::regex r("^(http|https):/");
     std::smatch match;
     // TODO: generalize using URI handlers
     if (std::regex_search(url, match, r)) {
-        scene.m_resourceLoad++;
-        startUrlRequest(url, [=, &scene](std::vector<char>&& rawData) {
+        scene->m_resourceLoad++;
+        startUrlRequest(url, [=](std::vector<char>&& rawData) {
                 auto ptr = (unsigned char*)(rawData.data());
```
Comment (hjanetzek) [inline core/src/scene/sceneLoader.cpp]: Ah - I see the issue. Shouldn't scene-loading block and wait until all resources are available?

Comment (tallytalwar) [inline core/src/scene/sceneLoader.cpp]: Yes and hence this: https://github.com/tangrams/tangram-es/issues/814

File: core/src/tangram.cpp (hunk 1 above)
Comment (karimnaaji) [inline core/src/tangram.cpp]: It stays valid in a sequential execution, but the address of the reference is copied in a lambda for deferred execution, where it potentially becomes invalid.

**Comment by tallytalwar** [comment]
Looking at this now.

File: core/src/tangram.cpp (hunk 1 above)
Comment (tallytalwar) [inline core/src/tangram.cpp]: I am not sure I get your comment here @hjanetzek about m_nextScene. Copying of m_nextScene happens on the same thread so it should be in sync.

Comment (tallytalwar) [inline core/src/tangram.cpp]: Ohh wait, just saw this is in `applySceneUpdates`, which can be called multiple times from any thread, yeah `m_nextScene` copy to `scene` might not be in sync in certain cases specially if multiple updates are being performed with multiple scene files.

**Comment by tallytalwar** [comment]
This looks fine, apart from the slight racecondition mentioned by @hjanetzek for copying of `m_newScene` to `scene`.

Even though this fixes the issue we need to have synchronous calls for URL fetching, which needs implementation for all platforms (refer #814).

**Comment by tallytalwar** [comment]
@hjanetzek you good with this change?

**Comment by karimnaaji** [comment]
Ready to merge if no more comments.

**Comment by blair1618** [comment]
I'm not clear how these changes would resolve the issue. A `std::shared_ptr<Scene>&` is still a non-owning reference (i.e. it doesn't add to the reference count of the `shared_ptr`) so wouldn't this cause the same dangling reference problem?

**Comment by karimnaaji** [comment]
The lambda where the problem happens would retain this shared pointer since it's given by copy instead of accessing the address of the reference to it.

**Comment by blair1618** [comment]
Interesting - looking at the offending lambda, I would've expected `[=]` to make a copy of a reference, since the local `scene` is a reference, but in a debugger I can see that the reference count on the `shared_ptr` increases after the lambda is created, so the problem would seem to be solved. 

LGTM

**Comment by karimnaaji** [comment]
Yes this was an interesting bug, it wasn't obvious to me at first too. I tested that on a small program to see how this was behaving clearly. Merging!
